// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTb6audkX9fedeQMbrPc-AnmUKdNVMBnc',
    appId: '1:794833609306:web:1cb344515b325d89906e63',
    messagingSenderId: '794833609306',
    projectId: 'flutter-auth-2c17a',
    authDomain: 'flutter-auth-2c17a.firebaseapp.com',
    storageBucket: 'flutter-auth-2c17a.appspot.com',
    measurementId: 'G-Z2V944QXF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz7B42UezJ-mXXEUs8azE2heI9OT1RA7E',
    appId: '1:794833609306:android:ba435e316de1d613906e63',
    messagingSenderId: '794833609306',
    projectId: 'flutter-auth-2c17a',
    storageBucket: 'flutter-auth-2c17a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2gfYGRMhPIkYD23Z775DeI71365xra7Q',
    appId: '1:794833609306:ios:a53965f66e346915906e63',
    messagingSenderId: '794833609306',
    projectId: 'flutter-auth-2c17a',
    storageBucket: 'flutter-auth-2c17a.appspot.com',
    iosClientId: '794833609306-eueti9g4ec70dpc4eg8mg4se4d6o48ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.therecipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2gfYGRMhPIkYD23Z775DeI71365xra7Q',
    appId: '1:794833609306:ios:a53965f66e346915906e63',
    messagingSenderId: '794833609306',
    projectId: 'flutter-auth-2c17a',
    storageBucket: 'flutter-auth-2c17a.appspot.com',
    iosClientId: '794833609306-eueti9g4ec70dpc4eg8mg4se4d6o48ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.therecipes',
  );
}
